# Generated by Django 4.0.2 on 2022-02-07 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('number', models.CharField(max_length=13)),
                ('password', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime.now)),
            ],
        ),
    ]
