# Generated by Django 4.0.2 on 2022-02-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0007_user_address_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.IntegerField(max_length=13),
        ),
    ]
