# Generated by Django 4.0.2 on 2022-02-05 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('fav', models.CharField(max_length=2)),
                ('crate_date', models.DateField(verbose_name=datetime.datetime(2022, 2, 6, 0, 11, 29, 909742))),
            ],
        ),
    ]
