# Generated by Django 4.0.2 on 2022-02-06 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_crate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='crate_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 2, 6, 17, 33, 17, 287871)),
        ),
        migrations.AlterField(
            model_name='product',
            name='fav',
            field=models.BooleanField(),
        ),
    ]
