# Generated by Django 4.0.2 on 2022-02-06 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_crate_date_alter_product_fav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='crate_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 17, 38, 18, 650945)),
        ),
    ]
