# Generated by Django 4.0.2 on 2022-02-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_image_product_imageurl_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='imageurl',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
