# Generated by Django 4.0.2 on 2022-02-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rename_imageurl_image_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.TextField(blank=True),
        ),
    ]
