# Generated by Django 4.0.2 on 2022-03-25 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_attribute_attributevalue_productattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='attribute_value',
            field=models.ForeignKey(limit_choices_to={'attribute': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.attribute')}, on_delete=django.db.models.deletion.CASCADE, to='shop.attributevalue'),
        ),
    ]
