# Generated by Django 4.0.2 on 2022-03-25 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_productattribute_attribute_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='attribute_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.attributevalue'),
        ),
    ]
