# Generated by Django 4.0.2 on 2022-03-25 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_productattribute_attribute_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='attribute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.attribute'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='attribute_value',
            field=models.ForeignKey(limit_choices_to={'attribute': models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.attribute')}, on_delete=django.db.models.deletion.CASCADE, to='shop.attributevalue'),
        ),
    ]
