# Generated by Django 4.0.2 on 2022-03-25 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_productattribute_attribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='attribute_value',
            field=models.ForeignKey(limit_choices_to={'attribute': 1}, on_delete=django.db.models.deletion.CASCADE, to='shop.attributevalue'),
        ),
    ]
