# Generated by Django 4.0.2 on 2022-04-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user_name',
            field=models.CharField(default='hossein', max_length=64),
            preserve_default=False,
        ),
    ]
