# Generated by Django 4.0.2 on 2022-04-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specialDiscount',
            field=models.BooleanField(default=False),
        ),
    ]
