# Generated by Django 4.0.2 on 2022-04-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_product_specialdiscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fav',
        ),
        migrations.AddField(
            model_name='product',
            name='Number_of_items_sold',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='initial_inventory',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(null=True),
        ),
    ]
