# Generated by Django 4.0.2 on 2022-04-08 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0012_alter_user_number'),
        ('shop', '0039_orderitem_unit_discount_alter_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.IntegerField(choices=[(1, 'Awaitingpayment'), (2, 'Processing'), (3, 'Delivered To The Post Office')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='trackingNumber',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users_api.user', to_field='number'),
        ),
    ]
