# Generated by Django 4.0.2 on 2022-04-15 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_product_group_alter_category_name_alter_group_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
