# Generated by Django 4.0.2 on 2022-04-15 15:14

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_alter_product_category_alter_product_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_time',
            field=django_jalali.db.models.jDateTimeField(null=True),
        ),
    ]
