# Generated by Django 4.0.2 on 2022-04-15 15:15

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_product_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_time',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True),
        ),
    ]
