# Generated by Django 4.0.2 on 2022-04-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_alter_product_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_time',
        ),
        migrations.AddField(
            model_name='comments',
            name='GregorianDataTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='submit_date',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='submit_time',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
