# Generated by Django 4.0.2 on 2022-04-15 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_rename_gregoriandatatime_comments_gregoriandatatime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='gregorianDataTime',
        ),
        migrations.RemoveField(
            model_name='order',
            name='submit_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='submit_time',
        ),
    ]
