# Generated by Django 4.0.2 on 2022-04-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_remove_order_gregoriandatatime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gregorianDataTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='submit_date',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='submit_time',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
