# Generated by Django 4.0.2 on 2022-04-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_order_gregoriandatatime_order_submit_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
