# Generated by Django 4.0.2 on 2022-04-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_order_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transferee_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='transferee_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='transferee_number',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
