# Generated by Django 4.0.2 on 2022-04-29 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0061_alter_comments_product_alter_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user_number',
            new_name='user',
        ),
    ]
