# Generated by Django 4.0.2 on 2022-07-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0063_alter_comments_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='imageUrl',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
