# Generated by Django 4.0.2 on 2022-07-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0064_orderitem_imageurl_orderitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.IntegerField(choices=[(1, 'Registered'), (2, 'Processing'), (3, 'Delivered To The Post Office')], default=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='imageUrl',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
